diaspora/config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'
require "sidekiq/cron/web"

Diaspora::Application.routes.draw do
  
  resources :report, except: %i(edit new show)

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  # Federation
  mount DiasporaFederation::Engine => "/"

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares, only: %i(create)

  resources :status_messages, :only => [:new, :create]
  
  resources :posts, only: %i(show destroy) do
    member do
      get :interactions
    end

    resource :participation, only: %i(create destroy)
    resources :poll_participations, only: :create
    resources :likes, only: %i(create destroy index)
    resources :comments, only: %i(new create destroy index)
  end

  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
#  get "activity" => "streams#activity", :as => "activity_stream"
#  get "stream" => "streams#multi", :as => "stream"
#  get "public" => "streams#public", :as => "public_stream"
#  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
#  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
#  get "liked" => "streams#liked", :as => "liked_stream"
#  get "commented" => "streams#commented", :as => "commented_stream"
#  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects, except: %i(index new edit) do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end
  
  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations, except: %i(edit update destroy)  do
    resources :messages, only: %i(create)
    delete 'visibility' => 'conversation_visibilities#destroy'
  end
  
  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  # Users and people

  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end
  
  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end

  controller :users do
    get "public/:username"          => :public,                  :as => :users_public
    get "getting_started"           => :getting_started,         :as => :getting_started
    get "confirm_email/:token"      => :confirm_email,           :as => :confirm_email
    get "privacy"                   => :privacy_settings,        :as => :privacy_settings
    put "privacy"                   => :update_privacy_settings, :as => :update_privacy_settings
    get "getting_started_completed" => :getting_started_completed
  end

#  devise_for :users, controllers: {sessions: "sessions",
#    :omniauth_callbacks => "omniauth_callbacks"}, 
#    skip: :registration
#    
#  devise_scope :user do
#    get "/users/sign_up" => "registrations#new",    :as => :new_user_registration
#    post "/users"        => "registrations#create", :as => :user_registration
#  end

  get "users/invitations"  => "invitations#new",    :as => "new_user_invitation"
  post "users/invitations" => "invitations#create", :as => "user_invitation"

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope "admins", controller: :admins do
    match :user_search, via: [:get, :post]
    get :admin_inviter
    get :weekly_user_stats
    get :stats, as: "pod_stats"
    get :dashboard, as: "admin_dashboard"
    get "add_invites/:invite_code_id" => "admins#add_invites", :as => "add_invites"
  end

  namespace :admin do
    resources :pods, only: :index do
      post :recheck
    end

    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts, only: %i(index)
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, only: %i(show index) do
    resources :status_messages, only: %i(new create)
    resources :photos, except:  %i(new update)
    get :contacts
    get :stream
    get :hovercard

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }
  get '/u/:username/profile_photo' => 'users#user_photo', :constraints => { :username => /[^\/]+/ }

  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

#  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'
#  get "/m", to: "home#force_mobile", as: "force_mobile"

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  # NodeInfo
  get ".well-known/nodeinfo", to: "node_info#jrd"
  get "nodeinfo/:version",    to: "node_info#document", as: "node_info", constraints: {version: /\d+\.\d+/}
  get "statistics",           to: "node_info#statistics"
  get "statistics",           to: "node_info#statistics"

  # Terms
  if AppConfig.settings.terms.enable? || Rails.env.test?
    get 'terms' => 'terms#index'
  end

  # Relay
  get ".well-known/x-social-relay" => "social_relay#well_known"

  # Startpage
#  root :to => 'home#show'
#  get "podmin", to: "home#podmin"

  namespace :api do
    namespace :openid_connect do
      resources :clients, only: :create
      get "clients/find", to: "clients#find"

      post "access_tokens", to: "token_endpoint#create"

      # Authorization Servers MUST support the use of the HTTP GET and POST methods at the Authorization Endpoint
      # See http://openid.net/specs/openid-connect-core-1_0.html#AuthResponseValidation
      resources :authorizations, only: %i(new create destroy)
      post "authorizations/new", to: "authorizations#new"
      get "user_applications", to: "user_applications#index"
      get "jwks.json", to: "id_tokens#jwks"
      match "user_info", to: "user_info#show", via: %i(get post)
    end
  end

  get ".well-known/webfinger", to: "api/openid_connect/discovery#webfinger"
  get ".well-known/openid-configuration", to: "api/openid_connect/discovery#configuration"
end

diaspora/app/controllers/people_controller.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class PeopleController < ApplicationController
  include GonHelper

  before_action :authenticate_user!, except: %i(show stream hovercard)
  before_action :find_person, only: %i(show stream hovercard)

  respond_to :html
  respond_to :json, :only => [:index, :show]

  rescue_from ActiveRecord::RecordNotFound do
    render :file => Rails.root.join('public', '404').to_s,
           :format => :html, :layout => false, :status => 404
  end

  rescue_from Diaspora::AccountClosed do
    respond_to do |format|
      format.any { redirect_to :back, :notice => t("people.show.closed_account") }
      format.json { render :nothing => true, :status => 410 } # 410 GONE
    end
  end

  helper_method :search_query

  def index
    @aspect = :search
    limit = params[:limit] ? params[:limit].to_i : 15

    @people = Person.search(search_query, current_user)

    respond_to do |format|
      format.json do
        @people = @people.limit(limit)
        render :json => @people
      end

      format.any(:html, :mobile) do
        #only do it if it is an email address
        if diaspora_id?(search_query)
          @people =  Person.where(:diaspora_handle => search_query.downcase)
          if @people.empty?
            Workers::FetchWebfinger.perform_async(search_query)
            @background_query = search_query.downcase
          end
        end
        @people = @people.paginate(:page => params[:page], :per_page => 15)
        @hashes = hashes_for_people(@people, @aspects)
      end
    end
  end

  def refresh_search
    @aspect = :search
    @people =  Person.where(:diaspora_handle => search_query.downcase)
    @answer_html = ""
    unless @people.empty?
      @hashes = hashes_for_people(@people, @aspects)

      self.formats = self.formats + [:html]
      @answer_html = render_to_string :partial => 'people/person', :locals => @hashes.first
    end
    render :json => { :search_count => @people.count, :search_html => @answer_html }.to_json
  end

  # renders the persons user profile page
  def show
    mark_corresponding_notifications_read if user_signed_in?

    @person_json = PersonPresenter.new(@person, current_user).as_json

    respond_to do |format|
      format.all do
        if user_signed_in?
          @contact = current_user.contact_for(@person)
        end
        gon.preloads[:person] = @person_json
        gon.preloads[:photos_count] = Photo.visible(current_user, @person).count(:all)
        gon.preloads[:contacts_count] = Contact.contact_contacts_for(current_user, @person).count(:all)
        respond_with @person, layout: "with_header"
      end

      format.mobile do
        @post_type = :all
        person_stream
        respond_with @person
      end

      format.json { render json: @person_json }
    end
  end

  def stream
    respond_to do |format|
      format.all { redirect_to person_path(@person) }
      format.json {
        render json: person_stream.stream_posts.map { |p| LastThreeCommentsDecorator.new(PostPresenter.new(p, current_user)) }
      }
    end
  end

  # hovercards fetch some the persons public profile data via json and display
  # it next to the avatar image in a nice box
  def hovercard
    respond_to do |format|
      format.all do
        redirect_to :action => "show", :id => params[:person_id]
      end

      format.json do
        render json: PersonPresenter.new(@person, current_user).hovercard
      end
    end
  end

  def retrieve_remote
    if params[:diaspora_handle]
      Workers::FetchWebfinger.perform_async(params[:diaspora_handle])
      render :nothing => true
    else
      render :nothing => true, :status => 422
    end
  end

  def contacts
    respond_to do |format|
      format.json { render nothing: true, status: 406 }

      format.any do
        @person = Person.find_by_guid(params[:person_id])

        if @person
          @contact = current_user.contact_for(@person)
          @contacts_of_contact = Contact.contact_contacts_for(current_user, @person)
          gon.preloads[:person] = PersonPresenter.new(@person, current_user).as_json
          gon.preloads[:photos_count] = Photo.visible(current_user, @person).count(:all)
          gon.preloads[:contacts_count] = @contacts_of_contact.count(:all)
          @contacts_of_contact = @contacts_of_contact.paginate(page: params[:page], per_page: (params[:limit] || 15))
          @hashes = hashes_for_people @contacts_of_contact, @aspects
          respond_with @person, layout: "with_header"
        else
          flash[:error] = I18n.t "people.show.does_not_exist"
          redirect_to people_path
        end
      end
    end
  end

  private

  def find_person
    username = params[:username]
    @person = if diaspora_id?(username)
        Person.where({
          diaspora_handle: username.downcase
        }).first
      else
        Person.find_from_guid_or_username({
          id: params[:id] || params[:person_id],
          username: username
        })
      end

    # view this profile on the home pod, if you don't want to sign in...
    authenticate_user! if remote_profile_with_no_user_session?
    raise ActiveRecord::RecordNotFound if @person.nil?
    raise Diaspora::AccountClosed if @person.closed_account?
  end

  def hashes_for_people(people, aspects)
    people.map {|person|
      {
        person:  person,
        contact: current_user.contact_for(person) || Contact.new(person: person),
        aspects: aspects
      }.tap {|hash|
        gon_load_contact(hash[:contact])
      }
    }
  end

  def search_query
    @search_query ||= params[:q] || params[:term] || ''
  end

  def diaspora_id?(query)
    !query.try(:match, /^(\w)*@([a-zA-Z0-9]|[-]|[.]|[:])*$/).nil?
  end

  def remote_profile_with_no_user_session?
    @person.try(:remote?) && !user_signed_in?
  end

  def mark_corresponding_notifications_read
    Notification.where(recipient_id: current_user.id, target_type: "Person", target_id: @person.id, unread: true).each do |n|
      n.set_read_state( true )
    end
  end

  def person_stream
    @stream ||= Stream::Person.new(current_user, @person, max_time: max_time)
  end
end

diaspora/app/helpers/people_helper.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module PeopleHelper
  include ERB::Util

  def search_header
    if search_query.blank?
      content_tag(:h2, t('people.index.no_results'))
    else
      content_tag(:h2, id: 'search_title') do
        t('people.index.results_for', search_term: content_tag(:span, search_query, class: 'term')).html_safe + looking_for_tag_link
      end
    end
  end

  def birthday_format(bday)
    if bday.year <= 1004
      I18n.l bday, format: I18n.t("date.formats.birthday")
    else
      I18n.l bday, format: I18n.t("date.formats.birthday_with_year")
    end
  end

  def person_link(person, opts={})
    opts[:class] ||= ""
    opts[:class] << " self" if defined?(user_signed_in?) && user_signed_in? && current_user.person == person
    opts[:class] << " hovercardable" if defined?(user_signed_in?) && user_signed_in? && current_user.person != person
    remote_or_hovercard_link = Rails.application.routes.url_helpers.person_path(person).html_safe
    "<a data-hovercard='#{remote_or_hovercard_link}' href='#{remote_or_hovercard_link}' class='#{opts[:class]}'>"\
      "#{html_escape_once(opts[:display_name] || person.name)}</a>"\
      .html_safe
  end

  def person_image_tag(person, size = :thumb_small)
    return "" if person.nil? || person.profile.nil?
    image_tag(person.profile.image_url(size), alt: person.name, class: "avatar img-responsive center-block",
              title: person.name, "data-person_id" => person.id)
  end

  def person_image_link(person, opts={})
    return "" if person.nil? || person.profile.nil?
    if opts[:to] == :photos
      link_to person_image_tag(person, opts[:size]), person_photos_path(person)
    else
      opts[:class] ||= ""
      opts[:class] << " self" if defined?(user_signed_in?) && user_signed_in? && current_user.person == person
      opts[:class] << " hovercardable" if defined?(user_signed_in?) && user_signed_in? && current_user.person != person
      remote_or_hovercard_link = Rails.application.routes.url_helpers.person_path(person).html_safe
      "<a href='#{remote_or_hovercard_link}' class='#{opts[:class]}' #{ ("target=" + opts[:target]) if opts[:target]}>
      #{person_image_tag(person, opts[:size])}
      </a>".html_safe
    end
  end

  # Rails.application.routes.url_helpers is needed since this is indirectly called from a model
  def local_or_remote_person_path(person, opts={})
    opts.merge!(:protocol => AppConfig.pod_uri.scheme, :host => AppConfig.pod_uri.authority)
    absolute = opts.delete(:absolute)

    if person.local?
      username = person.username
      unless username.include?('.')
        opts.merge!(:username => username)
        if absolute
          return Rails.application.routes.url_helpers.user_profile_url(opts)
        else
          return Rails.application.routes.url_helpers.user_profile_path(opts)
        end
      end
    end

    if absolute
      return Rails.application.routes.url_helpers.person_url(person, opts)
    else
      return Rails.application.routes.url_helpers.person_path(person, opts)
    end
  end
end

diaspora/app/views/people/_add_contact.haml
.well
  %strong
    = t(".invited_by")
  .media
    .pull-right
      = render partial: "aspect_memberships/aspect_membership_dropdown"
    .media-left
      = person_image_link(@person, size: :thumb_small, class: "media-object")
    .media-body
      = person_link(@person)

diaspora/app/views/people/_index.html.haml
#people_stream
  - people.each do |person|
    .media.stream_element{:id => person.id}
      .media-object.pull-left
        = person_image_link(person, :size => :thumb_small)
      .media-body
        = person_link(person, :class => 'name')
        .info.diaspora_handle
          = person.diaspora_handle
        .info.tags
          = Diaspora::Taggable.format_tags(person.profile.tag_string)

  = will_paginate people, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer

diaspora/app/views/people/_person.html.haml
.media.stream_element{id: person.id}
  .pull-right
    = render partial: 'people/relationship_action',
             locals: { person: person,
                          :current_user => current_user }
  .media-object.pull-left
    = person_image_link(person, size: :thumb_small)
  .media-body
    = person_link(person)
    .info.diaspora_handle
      = person.diaspora_handle
    .info.tags
      = Diaspora::Taggable.format_tags(person.profile.tag_string)
  .clearfix

diaspora/app/views/people/_person.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.stream_element{id: person.id}
  .content
    .media
      .media-left
        = person_image_link(person, size: :thumb_small, class: "media-object")
      .media-body
        %span.from
          = person_link(person, size: :thumb_small)
        .info
          = link_to person.diaspora_handle, local_or_remote_person_path(person), class: "black"

diaspora/app/views/people/_relationship_action.haml
- unless person == current_user.person
  .aspect_membership_dropdown.placeholder{data: {person_id: person.id}}
-else
  %span.thats_you
    = t("people.person.thats_you")

diaspora/app/views/people/contacts.haml
- content_for :page_title do
  = @person.name

.container-fluid#profile_container
  .row
    .col-md-3
      #profile
        -# here be JS

    .col-md-9
      .profile_header
        -# more JS

      .stream_container
        #people_stream.stream
          - @hashes.each do |hash|
            = render partial: 'people/person', locals: hash
        = will_paginate @contacts_of_contact, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

      %a.entypo-chevron-up.back-to-top#back-to-top{title: "#{t('layouts.application.back_to_top')}", href: "#"}

-if user_signed_in? && @person
  #new_status_message_pane
    = render 'shared/modal',
      path: new_status_message_path(:person_id => @person.id),
      title: t('status_messages.new.mentioning', person: @person.name),
      id: 'mentionModal'

  -if @contact
    #new_conversation_pane
      = render 'shared/modal',
        path: new_conversation_path(:contact_id => @contact.id, name: @contact.person.name, modal: true),
        title: t('conversations.index.new_conversation'),
        id: 'conversationModal'

diaspora/app/views/people/index.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = t('search')

- content_for :head do
  = javascript_include_tag 'contact-list'

.container#people_search
  .row
    .page-header
      = search_header
  .row
    .col-md-8
      #people_stream.stream
        - if @hashes.empty?
          - if @background_query.present?

            / TODO this is gross, and should be extracted!
            :javascript
              $(document).ready( function() {
                List.startSearchDelay('#{@background_query}')
              } );

            %p
              = t(".searching")
              .loader
                .spinner
          - else
            %p
              = t('.no_one_found')
        - else
          - for hash in @hashes
            = render partial: 'people/person', locals: hash

          = will_paginate(@people)

        %a.entypo-chevron-up.back-to-top#back-to-top{title: "#{t('layouts.application.back_to_top')}", href: "#"}

    .col-md-4
      - if AppConfig.settings.invitations.open?
        %h4
          = t('.couldnt_find_them')
        %p
          = t('.search_handle')
        %h4
          = t('.send_invite')
        = render "shared/invitations"

diaspora/app/views/people/index.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = t('search')

.search-mobile
  = form_tag(search_path, :method => 'get') do
    %div{:data => {:role => 'fieldcontain', :inline => 'true'}}
      = search_field_tag :q, nil, :placeholder => t('find_people'), :class => 'search'
    = submit_tag t('search'), 'data-inline' => 'true', :class => 'btn'

- if params[:q].blank?
  %h4
    = t('.no_results')
- else
  %h4#search_title
    = t('.results_for', search_term: params[:q])

  - if @hashes.empty?
    %p
      =t('.no_one_found')

  - else
    #people_stream.stream
      - for hash in @hashes
        = render :partial => 'people/person', :locals => hash

    = will_paginate @people, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer

diaspora/app/views/people/show.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = @person.name

.container-fluid#profile_container
  .row
    .col-md-3
      .sidebar.profile-sidebar#profile
        -# here be JS

    .col-md-9
      .profile_header
        -# more JS

      .stream_container

        - if user_signed_in? && current_user.person.id == @person.id && !current_page?(person_photos_path(@person))
          = render 'publisher/publisher', publisher_aspects_for(nil)

        .stream.clearfix#main_stream
          -# JS

        #paginate
          %span.loader.hidden
            .spinner

      %a.entypo-chevron-up.back-to-top#back-to-top{title: "#{t('layouts.application.back_to_top')}", href: "#"}

-if user_signed_in? && @person
  #new_status_message_pane
    = render 'shared/modal',
      path: new_status_message_path(:person_id => @person.id),
      title: t('status_messages.new.mentioning', person: @person.name),
      id: 'mentionModal'

  -if @contact
    #new_conversation_pane
      = render 'shared/modal',
        path: new_conversation_path(:contact_id => @contact.id, name: @contact.person.name, modal: true),
        title: t('conversations.index.new_conversation'),
        id: 'conversationModal'

diaspora/app/views/people/show.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#author_info.header-full-width
  = person_image_tag @person, :thumb_medium
  .content
    %h2
      = @person.name
    %span.description
      = @person.diaspora_handle
    - if user_signed_in? && @person != current_user.person
      = render 'aspect_memberships/aspect_membership_dropdown'
    .clear
  .bottom-bar
    - if !@person.tag_string.blank? && user_signed_in?
      = Diaspora::Taggable.format_tags(@person.tag_string)

- if @post_type == :photos
  = render "photos/index", photos: @posts
- else
  .stream#main_stream
    - if @stream.stream_posts.length > 0
      = render "shared/stream", posts: @stream.stream_posts
      = render "shared/stream_more_button"
    - else
      .dull
      - if user_signed_in? && (current_user.person != @person)
        = t(".has_not_shared_with_you_yet", name: @person.first_name)