diaspora/config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'
require "sidekiq/cron/web"

Diaspora::Application.routes.draw do
  
  resources :report, except: %i(edit new show)

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  # Federation
  mount DiasporaFederation::Engine => "/"

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares, only: %i(create)

  resources :status_messages, :only => [:new, :create]
  
  resources :posts, only: %i(show destroy) do
    member do
      get :interactions
    end

    resource :participation, only: %i(create destroy)
    resources :poll_participations, only: :create
    resources :likes, only: %i(create destroy index)
    resources :comments, only: %i(new create destroy index)
  end

  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
#  get "activity" => "streams#activity", :as => "activity_stream"
#  get "stream" => "streams#multi", :as => "stream"
#  get "public" => "streams#public", :as => "public_stream"
#  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
#  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
#  get "liked" => "streams#liked", :as => "liked_stream"
#  get "commented" => "streams#commented", :as => "commented_stream"
#  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects, except: %i(index new edit) do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end
  
  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations, except: %i(edit update destroy)  do
    resources :messages, only: %i(create)
    delete 'visibility' => 'conversation_visibilities#destroy'
  end
  
  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  # Users and people

  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end
  
  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end

  controller :users do
    get "public/:username"          => :public,                  :as => :users_public
    get "getting_started"           => :getting_started,         :as => :getting_started
    get "confirm_email/:token"      => :confirm_email,           :as => :confirm_email
    get "privacy"                   => :privacy_settings,        :as => :privacy_settings
    put "privacy"                   => :update_privacy_settings, :as => :update_privacy_settings
    get "getting_started_completed" => :getting_started_completed
  end

#  devise_for :users, controllers: {sessions: "sessions",
#    :omniauth_callbacks => "omniauth_callbacks"}, 
#    skip: :registration
#    
#  devise_scope :user do
#    get "/users/sign_up" => "registrations#new",    :as => :new_user_registration
#    post "/users"        => "registrations#create", :as => :user_registration
#  end

  get "users/invitations"  => "invitations#new",    :as => "new_user_invitation"
  post "users/invitations" => "invitations#create", :as => "user_invitation"

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope "admins", controller: :admins do
    match :user_search, via: [:get, :post]
    get :admin_inviter
    get :weekly_user_stats
    get :stats, as: "pod_stats"
    get :dashboard, as: "admin_dashboard"
    get "add_invites/:invite_code_id" => "admins#add_invites", :as => "add_invites"
  end

  namespace :admin do
    resources :pods, only: :index do
      post :recheck
    end

    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts, only: %i(index)
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, only: %i(show index) do
    resources :status_messages, only: %i(new create)
    resources :photos, except:  %i(new update)
    get :contacts
    get :stream
    get :hovercard

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }
  get '/u/:username/profile_photo' => 'users#user_photo', :constraints => { :username => /[^\/]+/ }

  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

#  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'
#  get "/m", to: "home#force_mobile", as: "force_mobile"

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  # NodeInfo
  get ".well-known/nodeinfo", to: "node_info#jrd"
  get "nodeinfo/:version",    to: "node_info#document", as: "node_info", constraints: {version: /\d+\.\d+/}
  get "statistics",           to: "node_info#statistics"
  get "statistics",           to: "node_info#statistics"

  # Terms
  if AppConfig.settings.terms.enable? || Rails.env.test?
    get 'terms' => 'terms#index'
  end

  # Relay
  get ".well-known/x-social-relay" => "social_relay#well_known"

  # Startpage
#  root :to => 'home#show'
#  get "podmin", to: "home#podmin"

  namespace :api do
    namespace :openid_connect do
      resources :clients, only: :create
      get "clients/find", to: "clients#find"

      post "access_tokens", to: "token_endpoint#create"

      # Authorization Servers MUST support the use of the HTTP GET and POST methods at the Authorization Endpoint
      # See http://openid.net/specs/openid-connect-core-1_0.html#AuthResponseValidation
      resources :authorizations, only: %i(new create destroy)
      post "authorizations/new", to: "authorizations#new"
      get "user_applications", to: "user_applications#index"
      get "jwks.json", to: "id_tokens#jwks"
      match "user_info", to: "user_info#show", via: %i(get post)
    end
  end

  get ".well-known/webfinger", to: "api/openid_connect/discovery#webfinger"
  get ".well-known/openid-configuration", to: "api/openid_connect/discovery#configuration"
end

diaspora/app/views/admins/_admin_bar.haml
- content_for :head do
  = stylesheet_link_tag :admin

%h2= t(".pages")

%ul#admin_nav.nav.nav-pills.nav-stacked
  %li{role: "presentation", class: current_page?(admin_dashboard_path) && "active"}
    = link_to t(".dashboard"), admin_dashboard_path
  %li{role: "presentation", class: current_page?(user_search_path) && "active"}
    = link_to t(".user_search"), user_search_path
  %li{role: "presentation", class: current_page?(weekly_user_stats_path) && "active"}
    = link_to t(".weekly_user_stats"), weekly_user_stats_path
  %li{role: "presentation", class: current_page?(pod_stats_path) && "active"}
    = link_to t(".pod_stats"), pod_stats_path
  %li{role: "presentation", class: current_page?(report_index_path) && "active"}
    = link_to t(".report"), report_index_path
  %li{role: "presentation", class: current_page?(admin_pods_path) && "active"}
    = link_to t(".pod_network"), admin_pods_path
  %li{role: "presentation", class: current_page?(sidekiq_path) && "active"}
    = link_to t(".sidekiq_monitor"), sidekiq_path

diaspora/app/views/admins/_user_entry.haml
%li.user.media
  %div.pull-left
    - if user.person
      %span.media-object
        = person_image_tag(user.person, size: :thumb_small)

  %div.media-body.row
    %div.pull-right
      %span.label.label-default
        = t('.id')
        = user.id
      %span.label.label-info
        = t('.guid')
        = user.person.guid if user.person

    %h4.media-heading
      = user.person.name if user.person

    %div.pull-right
      .unstyled.text-right.actions
        = link_to t('admins.user_search.view_profile'), person_path(user.person), class: 'btn btn-default btn-block btn-xs'
        = link_to t('admins.user_search.add_invites'), add_invites_path(user.invitation_code), class: 'btn btn-info btn-block btn-xs'
        - unless user.person.closed_account
          = link_to t('admins.user_search.close_account'), admin_close_account_path(user), method: :post, data: { confirm: t('admins.user_search.are_you_sure') }, class: 'btn btn-danger btn-block btn-xs'

        - unless user.closed_account?
          - unless user.access_locked?
            = link_to t('admins.user_search.lock_account'), admin_lock_account_path(user), method: :post, data: { confirm: t('admins.user_search.are_you_sure_lock_account') }, class: 'btn btn-danger btn-block btn-xs'
          - else
            = link_to t('admins.user_search.unlock_account'), admin_unlock_account_path(user), method: :post, data: { confirm: t('admins.user_search.are_you_sure_unlock_account') }, class: 'btn btn-danger btn-block btn-xs'

    %div.row
      %div.col-md-5
        %dl.dl-horizontal
          %dt= t('username')
          %dd= user.username
          %dt= t('.email')
          %dd= user.email
          %dt= t('.diaspora_handle')
          %dd= user.person.diaspora_handle
          %dt= t('.last_seen')
          %dd= user.last_seen || t('.unknown')
          -if user.invited_by.present?
            %dt= t('.invite_token')
            %dd= invite_code_url(user.invited_by.invitation_code)
          %dt= t('.account_closed')
          %dd
            - if user.person.closed_account
              %span.label.label-warning= t('.yes')
            - else
              %span.label.label-success= t('.no')
          %dt= t('.nsfw')
          %dd
            - if user.person.profile.nsfw
              %span.label.label-warning= t('.yes')
            - else
              %span.label.label-success= t('.no')

        %h4= t('layouts.header.profile')

        %dl.dl-horizontal
          %dt= t('people.profile_sidebar.born')
          %dd= user.person.profile.birthday
          %dt= t('people.profile_sidebar.gender')
          %dd= user.person.profile.gender
          %dt= t('people.profile_sidebar.location')
          %dd= user.person.profile.location
          %dt= t('people.profile_sidebar.bio')
          %dd= user.person.profile.bio

diaspora/app/views/admins/dashboard.html.haml
.container
  .row
    .col-md-3
      = render partial: "admins/admin_bar"
    .col-md-9
      #pod-status
        %h2
          = t(".pod_status")
        .alert.alert-info{role: "alert"}
          = t(".fetching_diaspora_version")

diaspora/app/views/admins/pods.html.haml
.container
  .row
    .col-md-3
      = render partial: "admins/admin_bar"

    .col-md-9
      %h2
        = t(".pod_network")

      #pod-alerts
        / filled by backbonejs

      #pod-list
        / filled by backbonejs

diaspora/app/views/admins/stats.html.haml
.container
  .row
    .col-md-3
      = render partial: "admins/admin_bar"
    .col-md-9
      %h1= t('.usage_statistic')

      .pull-right
        = form_tag('/admins/stats', :method => 'get', class: 'form-inline') do
          %select.form-control{name: "range"}
            %option{:value => 'daily', :selected => ('selected' if params[:range] == 'daily')}
              = t('.daily')
            %option{:value => 'week', :selected => ('selected' if params[:range] == 'week')}
              = t('.week')
            %option{:value => '2weeks', :selected => ('selected' if params[:range] == '2weeks')}
              = t('.2weeks')
            %option{:value => 'month', :selected => ('selected' if params[:range] == 'month')}
              = t('.month')

          = submit_tag t('.go'), class: 'btn btn-primary'

      %h3
        != t('.display_results', :segment => @segment)

      .row
        - [:posts, :comments, :aspect_memberships, :users].each do |name|
          - model = eval("@#{name.to_s}")
          - if name == :aspect_memberships
            - name = t('.shares', :count => model[:yesterday])
          - if name == :posts
            - name = t('.posts', :count => model[:yesterday])
          - if name == :comments
            - name = t('.comments', :count => model[:yesterday])
          - if name == :users
            - name = t('.users', :count => model[:yesterday])

          .col-md-3
            %h2{:style => 'font-weight:bold;'}
              = name.to_s
            %h4
              = model[:day_before]
              %span.percent_change{:class => (model[:change] > 0 ? "green" : "red")}
                = "(#{model[:change]}%)"

      .row
        .col-md-12
          %p.alert.alert-info.text-center{role: "alert"}
            != t('.current_segment', :post_yest => @posts[:yesterday]/@user_count.to_f, :post_day => @posts[:day_before]/@user_count.to_f)

      .row
        .col-md-12
          %h3= t('.50_most')
          %ul
          - @popular_tags.each do |name,count|
            %li
              != t('.tag_name', :name_tag => name, :count_tag => count)

diaspora/app/views/admins/user_search.html.haml
.container
  .row
    .col-md-3
      = render partial: "admins/admin_bar"
    .col-md-9
      .row
        .user_search.col-md-8
          %h3= t('admins.admin_bar.user_search')
          = form_for @search, url: {action: 'user_search'}, html: {method: :get, class: 'form-horizontal'} do |f|
            .form-group
              = f.label :username, t('username'), class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :username, class: "form-control"

            .form-group
              = f.label :email, t('email'), class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :email, class: "form-control"

            .form-group
              = f.label :guid, t('admins.user_entry.guid'), class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :guid, class: "form-control"

            .form-group
              .col-sm-offset-2.col-sm-10
                = f.label :under13 do
                  = f.check_box :under13
                  = t(".under_13")
            .form-group
              .clearfix.col-sm-12
                = submit_tag t("admins.stats.go"), class: "btn btn-primary pull-right"

        .more_invites.col-md-4
          %h3= t("shared.invitations.invites")
          #add-invites-section.clearfix
            != t(".you_currently", count: current_user.invitation_code.count,
                link: link_to(t(".add_invites"), add_invites_path(current_user.invitation_code),
                class: "btn btn-link pull-right"))

          = form_tag "admin_inviter", method: :get, class: "form-horizontal" do
            .form-group
              %label.col-sm-4.control-label
                = t(".email_to")
              .col-sm-8
                = text_field_tag "identifier", nil, class: "form-control"
            .form-group
              .clearfix.col-md-12
                = submit_tag t(".invite"), class: "btn btn-default pull-right"

      .row
        .col-md-12
          .alert.alert-info.text-center{role: "alert"}
            = t(".users", count: @users.count)

      .row
        .users.col-md-12
          %ul.media-list
            - @users.each do |user|
              = render partial: 'user_entry', locals: { user: user }

diaspora/app/views/admins/weekly_user_stats.haml
.container
  .row
    .col-md-3
      = render partial: "admins/admin_bar"
    .col-md-9
      %h2
        = t('.current_server', date: Time.now.to_date)

      .pull-right
        = form_tag('/admins/weekly_user_stats', method: 'get', class: 'form-inline') do
          = select_tag(:week, options_for_select(@created_users_by_week.keys.reverse, @selected_week), class: "form-control")
          = submit_tag t('admins.stats.go'), class: 'btn btn-primary'

      = t('.amount_of', count: @counter)
      %br
      - @created_users_by_week[@selected_week].each do |m|
        = link_to m, "/u/#{m}"
        %br