diaspora/config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'
require "sidekiq/cron/web"

Diaspora::Application.routes.draw do
  
  resources :report, except: %i(edit new show)

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  # Federation
  mount DiasporaFederation::Engine => "/"

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares, only: %i(create)

  resources :status_messages, :only => [:new, :create]
  
  resources :posts, only: %i(show destroy) do
    member do
      get :interactions
    end

    resource :participation, only: %i(create destroy)
    resources :poll_participations, only: :create
    resources :likes, only: %i(create destroy index)
    resources :comments, only: %i(new create destroy index)
  end

  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
#  get "activity" => "streams#activity", :as => "activity_stream"
#  get "stream" => "streams#multi", :as => "stream"
#  get "public" => "streams#public", :as => "public_stream"
#  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
#  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
#  get "liked" => "streams#liked", :as => "liked_stream"
#  get "commented" => "streams#commented", :as => "commented_stream"
#  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects, except: %i(index new edit) do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end
  
  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations, except: %i(edit update destroy)  do
    resources :messages, only: %i(create)
    delete 'visibility' => 'conversation_visibilities#destroy'
  end
  
  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  # Users and people

  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end
  
  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end

  controller :users do
    get "public/:username"          => :public,                  :as => :users_public
    get "getting_started"           => :getting_started,         :as => :getting_started
    get "confirm_email/:token"      => :confirm_email,           :as => :confirm_email
    get "privacy"                   => :privacy_settings,        :as => :privacy_settings
    put "privacy"                   => :update_privacy_settings, :as => :update_privacy_settings
    get "getting_started_completed" => :getting_started_completed
  end

#  devise_for :users, controllers: {sessions: "sessions",
#    :omniauth_callbacks => "omniauth_callbacks"}, 
#    skip: :registration
#    
#  devise_scope :user do
#    get "/users/sign_up" => "registrations#new",    :as => :new_user_registration
#    post "/users"        => "registrations#create", :as => :user_registration
#  end

  get "users/invitations"  => "invitations#new",    :as => "new_user_invitation"
  post "users/invitations" => "invitations#create", :as => "user_invitation"

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope "admins", controller: :admins do
    match :user_search, via: [:get, :post]
    get :admin_inviter
    get :weekly_user_stats
    get :stats, as: "pod_stats"
    get :dashboard, as: "admin_dashboard"
    get "add_invites/:invite_code_id" => "admins#add_invites", :as => "add_invites"
  end

  namespace :admin do
    resources :pods, only: :index do
      post :recheck
    end

    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts, only: %i(index)
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, only: %i(show index) do
    resources :status_messages, only: %i(new create)
    resources :photos, except:  %i(new update)
    get :contacts
    get :stream
    get :hovercard

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }
  get '/u/:username/profile_photo' => 'users#user_photo', :constraints => { :username => /[^\/]+/ }

  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

#  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'
#  get "/m", to: "home#force_mobile", as: "force_mobile"

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  # NodeInfo
  get ".well-known/nodeinfo", to: "node_info#jrd"
  get "nodeinfo/:version",    to: "node_info#document", as: "node_info", constraints: {version: /\d+\.\d+/}
  get "statistics",           to: "node_info#statistics"
  get "statistics",           to: "node_info#statistics"

  # Terms
  if AppConfig.settings.terms.enable? || Rails.env.test?
    get 'terms' => 'terms#index'
  end

  # Relay
  get ".well-known/x-social-relay" => "social_relay#well_known"

  # Startpage
#  root :to => 'home#show'
#  get "podmin", to: "home#podmin"

  namespace :api do
    namespace :openid_connect do
      resources :clients, only: :create
      get "clients/find", to: "clients#find"

      post "access_tokens", to: "token_endpoint#create"

      # Authorization Servers MUST support the use of the HTTP GET and POST methods at the Authorization Endpoint
      # See http://openid.net/specs/openid-connect-core-1_0.html#AuthResponseValidation
      resources :authorizations, only: %i(new create destroy)
      post "authorizations/new", to: "authorizations#new"
      get "user_applications", to: "user_applications#index"
      get "jwks.json", to: "id_tokens#jwks"
      match "user_info", to: "user_info#show", via: %i(get post)
    end
  end

  get ".well-known/webfinger", to: "api/openid_connect/discovery#webfinger"
  get ".well-known/openid-configuration", to: "api/openid_connect/discovery#configuration"
end

diaspora/app/models/contact.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Contact < ActiveRecord::Base
  include Diaspora::Federated::Base

  belongs_to :user
  validates :user, presence: true

  belongs_to :person
  validates :person, presence: true

  validates :person_id, uniqueness: {scope: :user_id}

  delegate :name, :diaspora_handle, :guid, :first_name,
           to: :person, prefix: true

  has_many :aspect_memberships, dependent: :destroy
  has_many :aspects, through: :aspect_memberships

  validate :not_contact_for_self,
           :not_blocked_user,
           :not_contact_with_closed_account

  before_destroy :destroy_notifications

  scope :all_contacts_of_person, ->(x) { where(person_id: x.id) }

  # contact.sharing is true when contact.person is sharing with contact.user
  scope :sharing, -> { where(sharing: true) }

  # contact.receiving is true when contact.user is sharing with contact.person
  scope :receiving, -> { where(receiving: true) }

  scope :for_a_stream, -> { includes(:aspects, person: :profile).order("profiles.last_name ASC") }

  scope :only_sharing, -> { sharing.where(receiving: false) }

  def destroy_notifications
    Notification.where(
      target_type:  "Person",
      target_id:    person_id,
      recipient_id: user_id,
      type:         "Notifications::StartedSharing"
    ).destroy_all
  end

  def contacts
    people = Person.arel_table
    incoming_aspects = Aspect.where(
      :user_id => self.person.owner_id,
      :contacts_visible => true).joins(:contacts).where(
        :contacts => {:person_id => self.user.person_id}).select('aspects.id')
    incoming_aspect_ids = incoming_aspects.map{|a| a.id}
    similar_contacts = Person.joins(:contacts => :aspect_memberships).where(
      :aspect_memberships => {:aspect_id => incoming_aspect_ids}).where(people[:id].not_eq(self.user.person.id)).select('DISTINCT people.*')
  end

  def mutual?
    sharing && receiving
  end

  def in_aspect?(aspect)
    if aspect_memberships.loaded?
      aspect_memberships.detect{ |am| am.aspect_id == aspect.id }
    elsif aspects.loaded?
      aspects.detect{ |a| a.id == aspect.id }
    else
      AspectMembership.exists?(:contact_id => self.id, :aspect_id => aspect.id)
    end
  end

  def self.contact_contacts_for(user, person)
    return none unless user

    if person == user.person
      user.contact_people
    else
      contact = user.contact_for(person)
      contact.try(:contacts) || none
    end
  end

  # Follows back if user setting is set so
  def receive(_recipient_user_ids)
    user.share_with(person, user.auto_follow_back_aspect) if user.auto_follow_back && !receiving
  end

  # object for local recipients
  def object_to_receive
    Contact.create_or_update_sharing_contact(person.owner, user.person)
  end

  # @return [Array<Person>] The recipient of the contact
  def subscribers
    [person]
  end

  # creates or updates a contact with active sharing flag. Returns nil if already sharing.
  def self.create_or_update_sharing_contact(recipient, sender)
    contact = recipient.contacts.find_or_initialize_by(person_id: sender.id)

    return if contact.sharing

    contact.update(sharing: true)
    contact
  end

  private

  def not_contact_with_closed_account
    errors.add(:base, "Cannot be in contact with a closed account") if person_id && person.closed_account?
  end

  def not_contact_for_self
    errors.add(:base, "Cannot create self-contact") if person_id && person.owner == user
  end

  def not_blocked_user
    errors.add(:base, "Cannot connect to an ignored user") if user && user.blocks.where(person_id: person_id).exists?
  end
end

diaspora/app/helpers/publisher_helper.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module PublisherHelper
  def remote?
    params[:controller] != "tags"
  end

  def all_aspects_selected?(selected_aspects)
    @all_aspects_selected ||= all_aspects.size == selected_aspects.size
  end

  def service_button(service)
    provider_title = I18n.t(
      "services.index.share_to",
      provider: service.provider.titleize)
    content_tag :div,
                class:   "btn btn-link service_icon dim",
                title:   "#{provider_title} (#{service.nickname})",
                id:      "#{service.provider}",
                maxchar: "#{service.class::MAX_CHARACTERS}",
                data:    {toggle: "tooltip", placement: "bottom"} do
      if service.provider == "wordpress"
        content_tag(:span, "", class: "social-media-logos-wordpress-16x16")
      else
        content_tag(:i, "", class: "entypo-social-#{ service.provider } small")
      end
    end
  end
end

diaspora/app/views/publisher/_aspect_dropdown.html.haml
.btn-group.aspect_dropdown
  %button.btn.btn-default.dropdown-toggle{ ! current_user.getting_started? ? {'data-toggle' => 'dropdown'} : {'data-toggle' => 'dropdown', title: popover_with_close_html("2. #{t('shared.public_explain.control_your_audience')}"), 'data-content'=> t('shared.public_explain.visibility_dropdown')} }
    - if publisher_public
      %i#visibility-icon.entypo-globe.small
      %span.text
        = t('public')
    - else
      %i#visibility-icon.entypo-lock.small
      %span.text
        - if all_aspects_selected?(selected_aspects)
          = t('all_aspects')
        - elsif selected_aspects.size == 1
          = selected_aspects.first.name
        - else
          = t('shared.aspect_dropdown.toggle', count: selected_aspects.size)
    %span.caret
  %ul.dropdown-menu.pull-right{ unSelectable: 'on' }

    %li.public.radio{"data-aspect_id" => "public", class: ("selected" if publisher_public)}
      %a
        %span.status_indicator
          %i.glyphicon.glyphicon-ok
        %span.text
          = t('public')
    %li.all_aspects.radio{"data-aspect_id" => "all_aspects", class: ("selected" if (!publisher_public && all_aspects_selected?(selected_aspects)))}
      %a
        %span.status_indicator
          %i.glyphicon.glyphicon-ok
        %span.text
          = t('all_aspects')
    %li.divider
    - for aspect in all_aspects
      %li.aspect_selector{ 'data-aspect_id' => aspect.id, class: !all_aspects_selected?(selected_aspects) && selected_aspects.include?(aspect) ? "selected" : "" }
        %a
          %span.status_indicator
            %i.glyphicon.glyphicon-ok
          %span.text
            = aspect.name

diaspora/app/views/publisher/_publisher.html.haml
-if publisher_explain
  :javascript
    $(document).ready(function() {
        if( app.publisher ) app.publisher.triggerGettingStarted();
      });

.row.publisher#publisher{class: ((aspect == :profile || publisher_open) ? "mention_popup" : "closed")}
  .content_creation
    = form_for(StatusMessage.new) do |status|
      = status.error_messages
      %params
        .publisher-textarea-wrapper#publisher_textarea_wrapper
          .mentions-input-box
            .mentions-box
              .mentions
            - if current_user.getting_started?
              = status.text_area :fake_text, :rows => 2, :value => h(publisher_formatted_text),
                :tabindex => 1, :placeholder => "#{t('contacts.index.start_a_conversation')}...",
                "data-title" => popover_with_close_html("1. " + t("shared.public_explain.share")),
                "data-content" => t("shared.public_explain.new_user_welcome_message"),
                "class" => "form-control"
            - else
              = status.text_area :fake_text, :rows => 2, :value => h(publisher_formatted_text),
                :tabindex => 1, :placeholder => "#{t('contacts.index.start_a_conversation')}...",
                "class" => "form-control"
            %input.typeahead-mention-box.hidden{type: "text"}
          = status.hidden_field :text, value: h(publisher_hidden_text), class: "clear_on_submit"

          .container-fluid.photodropzone-container#photodropzone_container
            %ul#photodropzone
          .location-container.form-group{style: "padding: 4px 6px;"}
            = hidden_field :location, :coords
          .poll-creator-container#poll_creator_container
            -# handlebars template
          #button_container
            .publisher-buttonbar#publisher-images
              .btn.btn-link.poll-creator#poll_creator{title: t("shared.publisher.poll.add_a_poll")}
                %i.entypo-bar-graph
              .btn.btn-link.file-upload#file-upload{title: t("shared.publisher.upload_photos")}
                %i.entypo-camera.publisher_image
              .btn.btn-link.locator#locator{title: t("shared.publisher.get_location")}
                %i.entypo-location.publisher_image
              .btn.btn-link.hide-location#hide_location{title: t("shared.publisher.remove_location")}
                %i.entypo-cross.publisher_image
            %span.markdownIndications
              != t("shared.publisher.formatWithMarkdown", markdown_link: link_to(t("help.markdown"),
                  "https://diasporafoundation.org/formatting", target: :blank))

      - if publisher_public
        = hidden_field_tag "aspect_ids[]", "public"
      - elsif all_aspects_selected?(selected_aspects)
        = hidden_field_tag "aspect_ids[]", "all_aspects"
      - else
        - for aspect_id in aspect_ids
          = hidden_field_tag "aspect_ids[]", aspect_id.to_s

      .hidden#publisher_spinner
        .loader
          .spinner
      .options_and_submit.col-sm-12
        .public_toggle.clearfix
          .btn-toolbar.pull-right
            = render partial: "publisher/aspect_dropdown", locals: {selected_aspects: selected_aspects}
            %button.btn.btn-group.btn-primary#submit= t("shared.publisher.share")

          .btn-toolbar.pull-right#publisher-service-icons
            - if current_user.services
              - current_user.services.each do |service|
                = service_button(service)
            .btn.btn-link.question_mark{title: t("shared.public_explain.manage"),
                           data: {toggle: "modal", target: "#publicExplainModal"}}
              %i.entypo-cog

    = link_to "", contacts_path(aspect_ids: aspect_ids), class: "selected_contacts_link hidden"

= render "shared/public_explain"

diaspora/app/views/publisher/_publisher.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= form_for StatusMessage.new, html: {class: "control-group", data: {ajax: false}} do |status|
  .form-group
    = status.hidden_field :provider_display_name, value: 'mobile'
    = status.text_area :text, placeholder: t('shared.publisher.whats_on_your_mind'), rows: 4, autofocus: "autofocus", class: "form-control"

  .form-group
    %span#publisher-service-icons
      - if current_user.services
        - for service in current_user.services
          = image_tag "social-media-logos/#{service.provider}-32x32.png",
            title: service.provider.titleize, class: "service_icon dim",
            id: "#{service.provider}", maxchar: "#{service.class::MAX_CHARACTERS}"

    %select{id: "aspect_ids_", class: "form-control", name: "aspect_ids[]"}
      %option{value: 'public'}
        = t('public')

      %option{value: 'all_aspects', selected: true}
        = t('all_aspects')

      - current_user.aspects.each do |aspect|
        %option{value: aspect.id}
          = "· #{aspect.name}"

    .clear
    #publisher_textarea_wrapper
      %ul#photodropzone
    #fileInfo-publisher

    #file-upload-publisher{title: t('shared.publisher.upload_photos'), class: 'btn btn-default'}
      %i.entypo-camera.middle
    #publisher_mobile
      = submit_tag t("shared.publisher.share"),
        class: "btn btn-primary",
        id: "submit_new_message",
        data: {"disable-with" => t("shared.publisher.posting")}
    .clearfix